# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loopers < Formula
  desc "The Circuit Breaker for AI API Billing"
  homepage "https://tryloopers.com"
  version "2.21.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/try-loopers/loopers-oss/releases/download/v2.21.3/loopers_Darwin_x86_64.tar.gz"
      sha256 "3cb7586d68e99d2802739aea7b1cd71312ec8f1771af53696ce639ab8bab3cca"

      define_method(:install) do
        bin.install "loopers"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/try-loopers/loopers-oss/releases/download/v2.21.3/loopers_Darwin_arm64.tar.gz"
      sha256 "7c911172518fbacd13c8e5237e1c32d74076ecff6c8a0ad378184285a7c5d0be"

      define_method(:install) do
        bin.install "loopers"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/try-loopers/loopers-oss/releases/download/v2.21.3/loopers_Linux_x86_64.tar.gz"
      sha256 "f37b3df2b5abef3c003068b3ffa371b1d7ac0c9afc5e294f4b971787922fef21"
      define_method(:install) do
        bin.install "loopers"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/try-loopers/loopers-oss/releases/download/v2.21.3/loopers_Linux_arm64.tar.gz"
      sha256 "4a8faf261ea57e2654720cfc148c67d68f3cb0420e542930717a396d0839ca21"
      define_method(:install) do
        bin.install "loopers"
      end
    end
  end
end
